version: "3.9"

services:
  formatter:
    build: .
    container_name: formatter_app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    command: >
      sh -c "
      python3 main.py --a house_multifeature.csv --skip-header &&
      python3 visualizer_flask/app.py
      "
